=== MaskedRiderW/l2jtw_pvp_server/dp/dist/game/data/xsd/tvtPatterns.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="pattern" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="1">
              <xs:element name="tvtEvent" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="TvTEventInstanceFile" minOccurs="1" maxOccurs="1">
                      <xs:complexType><xs:attribute name="value" type="xs:token" use="required"/></xs:complexType>
                    </xs:element>
                    <xs:element name="TvTEventParticipationNpcId" minOccurs="1" maxOccurs="1">
                      <xs:complexType><xs:attribute name="value" type="xs:token" use="required"/></xs:complexType>
                    </xs:element>
                    <xs:element name="TvTEventParticipationFee" minOccurs="1" maxOccurs="1">
                      <xs:complexType><xs:attribute name="value" type="xs:token" use="required"/></xs:complexType>
                    </xs:element>
                    <xs:element name="TvTEventParticipationNpcCoordinates" minOccurs="1" maxOccurs="1">
                      <xs:complexType><xs:attribute name="value" type="xs:token" use="required"/></xs:complexType>
                    </xs:element>
                    <xs:element name="TvTEventReward" minOccurs="1" maxOccurs="1">
                      <xs:complexType><xs:attribute name="value" type="xs:token" use="required"/></xs:complexType>
                    </xs:element>
                    <xs:element name="TvTDoorsToOpen" minOccurs="1" maxOccurs="1">
                      <xs:complexType><xs:attribute name="value" type="xs:token"/></xs:complexType>
                    </xs:element>
                    <xs:element name="TvTDoorsToClose" minOccurs="1" maxOccurs="1">
                      <xs:complexType><xs:attribute name="value" type="xs:token"/></xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="tvtEventTeam" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="TvTEventTeam1Name" minOccurs="1" maxOccurs="1">
                      <xs:complexType><xs:attribute name="value" type="xs:token" use="required"/></xs:complexType>
                    </xs:element>
                    <xs:element name="TvTEventTeam1Coordinates" minOccurs="1" maxOccurs="1">
                      <xs:complexType><xs:attribute name="value" type="xs:token" use="required"/></xs:complexType>
                    </xs:element>
                    <xs:element name="TvTEventTeam2Name" minOccurs="1" maxOccurs="1">
                      <xs:complexType><xs:attribute name="value" type="xs:token" use="required"/></xs:complexType>
                    </xs:element>
                    <xs:element name="TvTEventTeam2Coordinates" minOccurs="1" maxOccurs="1">
                      <xs:complexType><xs:attribute name="value" type="xs:token" use="required"/></xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="tvtManager" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="TvTEventParticipationTime" minOccurs="1" maxOccurs="1">
                      <xs:complexType><xs:attribute name="value" type="xs:token" use="required"/></xs:complexType>
                    </xs:element>
                    <xs:element name="TvTEventMeetingTime" minOccurs="1" maxOccurs="1">
                      <xs:complexType><xs:attribute name="value" type="xs:token" use="required"/></xs:complexType>
                    </xs:element>
                    <xs:element name="TvTEventRunningTime" minOccurs="1" maxOccurs="1">
                      <xs:complexType><xs:attribute name="value" type="xs:token" use="required"/></xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="value" type="xs:token" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MaskedRiderW/l2jtw_pvp_server/dp/dist/game/data/tvtPatterns.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/tvtPatterns.xsd">
	<pattern id="1" name="normal">
		<tvtEvent>
			<TvTEventInstanceFile value="coliseum.xml"/>
			<TvTEventParticipationNpcId value="70010"/>
			<TvTEventParticipationFee value="0,0"/>
			<TvTEventParticipationNpcCoordinates value="83425,148585,-3406"/>
			<TvTEventReward value="57,100000"/>
			<TvTDoorsToOpen value=""/>
			<TvTDoorsToClose value=""/>
		</tvtEvent>
		<tvtEventTeam>
			<TvTEventTeam1Name value="Team1"/>
			<TvTEventTeam1Coordinates value="148695,46725,-3414"/>
			<TvTEventTeam2Name value="Team2"/>
			<TvTEventTeam2Coordinates value="149999,46728,-3414"/>
		</tvtEventTeam>
		<tvtManager>
			<TvTEventParticipationTime value="1"/>
			<TvTEventMeetingTime value="1"/>
			<TvTEventRunningTime value="1"/>
		</tvtManager>
	</pattern>
	<pattern id="2" name="hard">
		<tvtEvent>
			<TvTEventInstanceFile value="coliseum.xml"/>
			<TvTEventParticipationNpcId value="70010"/>
			<TvTEventParticipationFee value="0,0"/>
			<TvTEventParticipationNpcCoordinates value="83425,148585,-3406"/>
			<TvTEventReward value="57,100000"/>
			<TvTDoorsToOpen value=""/>
			<TvTDoorsToClose value=""/>
		</tvtEvent>
		<tvtEventTeam>
			<TvTEventTeam1Name value="Team1"/>
			<TvTEventTeam1Coordinates value="148695,46725,-3414"/>
			<TvTEventTeam2Name value="Team2"/>
			<TvTEventTeam2Coordinates value="149999,46728,-3414"/>
		</tvtEventTeam>
		<tvtManager>
			<TvTEventParticipationTime value="1"/>
			<TvTEventMeetingTime value="1"/>
			<TvTEventRunningTime value="1"/>
		</tvtManager>
	</pattern>
</list>
